version: '3.7'

services:
  database:
    container_name: 'shopping_list_database'
    image: 'mongo:latest'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - shopping_list_mongodb:/data/db
  redis:
    container_name: 'shopping_list_redis'
    image: 'redis:latest'
    ports:
      - '6379:6379'

volumes:
  shopping_list_mongodb:
